# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_file_widget(object):
    def setupUi(self, file_widget):
        file_widget.setObjectName("file_widget")
        file_widget.resize(543, 569)
        self.verticalLayout = QtWidgets.QVBoxLayout(file_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.aspects = QtWidgets.QTabWidget(file_widget)
        self.aspects.setTabPosition(QtWidgets.QTabWidget.West)
        self.aspects.setObjectName("aspects")
        self.channels_tab = QtWidgets.QWidget()
        self.channels_tab.setObjectName("channels_tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.channels_tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.splitter = QtWidgets.QSplitter(self.channels_tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.channels_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.channels_layout.setContentsMargins(0, 0, 0, 0)
        self.channels_layout.setObjectName("channels_layout")
        self.verticalLayout_8.addWidget(self.splitter)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aspects.addTab(self.channels_tab, icon, "")
        self.convert_tab = QtWidgets.QWidget()
        self.convert_tab.setObjectName("convert_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.convert_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.convert_split_size = QtWidgets.QDoubleSpinBox(self.convert_tab)
        self.convert_split_size.setDecimals(3)
        self.convert_split_size.setObjectName("convert_split_size")
        self.gridLayout_2.addWidget(self.convert_split_size, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.convert_tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.convert_tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 2)
        self.convert_split = QtWidgets.QCheckBox(self.convert_tab)
        self.convert_split.setChecked(True)
        self.convert_split.setObjectName("convert_split")
        self.gridLayout_2.addWidget(self.convert_split, 3, 0, 1, 1)
        self.convert_compression = QtWidgets.QComboBox(self.convert_tab)
        self.convert_compression.setObjectName("convert_compression")
        self.gridLayout_2.addWidget(self.convert_compression, 2, 1, 1, 1)
        self.convert_format = QtWidgets.QComboBox(self.convert_tab)
        self.convert_format.setMinimumSize(QtCore.QSize(200, 0))
        self.convert_format.setObjectName("convert_format")
        self.gridLayout_2.addWidget(self.convert_format, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.convert_tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.convert_tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.convert_tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 5, 0, 1, 2)
        self.convert_btn = QtWidgets.QPushButton(self.convert_tab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/convert.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.convert_btn.setIcon(icon1)
        self.convert_btn.setObjectName("convert_btn")
        self.gridLayout_2.addWidget(self.convert_btn, 6, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.aspects.addTab(self.convert_tab, icon1, "")
        self.cut_tab = QtWidgets.QWidget()
        self.cut_tab.setObjectName("cut_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.cut_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cut_split_size = QtWidgets.QDoubleSpinBox(self.cut_tab)
        self.cut_split_size.setObjectName("cut_split_size")
        self.gridLayout_3.addWidget(self.cut_split_size, 7, 1, 1, 1)
        self.cut_split = QtWidgets.QCheckBox(self.cut_tab)
        self.cut_split.setChecked(True)
        self.cut_split.setObjectName("cut_split")
        self.gridLayout_3.addWidget(self.cut_split, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.cut_tab)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 10, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.cut_tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 7, 0, 1, 1)
        self.cut_btn = QtWidgets.QPushButton(self.cut_tab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cut_btn.setIcon(icon2)
        self.cut_btn.setObjectName("cut_btn")
        self.gridLayout_3.addWidget(self.cut_btn, 9, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.cut_tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 3, 0, 1, 2)
        self.line_4 = QtWidgets.QFrame(self.cut_tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 8, 0, 1, 2)
        self.cut_compression = QtWidgets.QComboBox(self.cut_tab)
        self.cut_compression.setObjectName("cut_compression")
        self.gridLayout_3.addWidget(self.cut_compression, 5, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.cut_tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.cut_tab)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 4, 0, 1, 1)
        self.cut_start = QtWidgets.QDoubleSpinBox(self.cut_tab)
        self.cut_start.setDecimals(6)
        self.cut_start.setObjectName("cut_start")
        self.gridLayout_3.addWidget(self.cut_start, 1, 1, 1, 1)
        self.cut_format = QtWidgets.QComboBox(self.cut_tab)
        self.cut_format.setObjectName("cut_format")
        self.gridLayout_3.addWidget(self.cut_format, 4, 1, 1, 1)
        self.cut_stop = QtWidgets.QDoubleSpinBox(self.cut_tab)
        self.cut_stop.setDecimals(6)
        self.cut_stop.setObjectName("cut_stop")
        self.gridLayout_3.addWidget(self.cut_stop, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.cut_tab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 0, 1, 1)
        self.cut_interval = QtWidgets.QLabel(self.cut_tab)
        self.cut_interval.setObjectName("cut_interval")
        self.gridLayout_3.addWidget(self.cut_interval, 0, 0, 1, 2)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.aspects.addTab(self.cut_tab, icon2, "")
        self.export_tab = QtWidgets.QWidget()
        self.export_tab.setObjectName("export_tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.export_tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_21 = QtWidgets.QLabel(self.export_tab)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 0, 0, 1, 1)
        self.export_type = QtWidgets.QComboBox(self.export_tab)
        self.export_type.setObjectName("export_type")
        self.gridLayout_6.addWidget(self.export_type, 0, 1, 1, 1)
        self.single_time_base = QtWidgets.QCheckBox(self.export_tab)
        self.single_time_base.setObjectName("single_time_base")
        self.gridLayout_6.addWidget(self.single_time_base, 2, 0, 1, 1)
        self.time_from_zero = QtWidgets.QCheckBox(self.export_tab)
        self.time_from_zero.setObjectName("time_from_zero")
        self.gridLayout_6.addWidget(self.time_from_zero, 3, 0, 1, 1)
        self.empty_channels = QtWidgets.QComboBox(self.export_tab)
        self.empty_channels.setObjectName("empty_channels")
        self.gridLayout_6.addWidget(self.empty_channels, 7, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.export_tab)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 4, 0, 1, 1)
        self.use_display_names = QtWidgets.QCheckBox(self.export_tab)
        self.use_display_names.setObjectName("use_display_names")
        self.gridLayout_6.addWidget(self.use_display_names, 6, 0, 1, 1)
        self.export_raster = QtWidgets.QDoubleSpinBox(self.export_tab)
        self.export_raster.setDecimals(6)
        self.export_raster.setObjectName("export_raster")
        self.gridLayout_6.addWidget(self.export_raster, 4, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 2, 2, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.export_tab)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_6.addWidget(self.line_10, 9, 0, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 8, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.export_tab)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 7, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem7, 11, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.export_tab)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 8, 0, 1, 1)
        self.export_btn = QtWidgets.QPushButton(self.export_tab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.export_btn.setIcon(icon3)
        self.export_btn.setObjectName("export_btn")
        self.gridLayout_6.addWidget(self.export_btn, 10, 0, 1, 1)
        self.mat_format = QtWidgets.QComboBox(self.export_tab)
        self.mat_format.setObjectName("mat_format")
        self.gridLayout_6.addWidget(self.mat_format, 8, 1, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.export_tab)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_6.addWidget(self.line_9, 5, 0, 1, 2)
        self.line_11 = QtWidgets.QFrame(self.export_tab)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_6.addWidget(self.line_11, 1, 0, 1, 2)
        self.verticalLayout_7.addLayout(self.gridLayout_6)
        self.aspects.addTab(self.export_tab, icon3, "")
        self.filter_tab = QtWidgets.QWidget()
        self.filter_tab.setObjectName("filter_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.filter_tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.filter_layout = QtWidgets.QGridLayout()
        self.filter_layout.setContentsMargins(5, 5, 5, 5)
        self.filter_layout.setObjectName("filter_layout")
        self.filter_btn = QtWidgets.QPushButton(self.filter_tab)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/filter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filter_btn.setIcon(icon4)
        self.filter_btn.setObjectName("filter_btn")
        self.filter_layout.addWidget(self.filter_btn, 7, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.filter_layout.addItem(spacerItem8, 8, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.filter_layout.addItem(spacerItem9, 2, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.filter_layout.addItem(spacerItem10, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.filter_tab)
        self.label_12.setObjectName("label_12")
        self.filter_layout.addWidget(self.label_12, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.filter_tab)
        self.label_11.setObjectName("label_11")
        self.filter_layout.addWidget(self.label_11, 2, 1, 1, 1)
        self.filter_compression = QtWidgets.QComboBox(self.filter_tab)
        self.filter_compression.setObjectName("filter_compression")
        self.filter_layout.addWidget(self.filter_compression, 2, 2, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.filter_tab)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.filter_layout.addWidget(self.line_8, 3, 1, 1, 2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.filter_layout.addItem(spacerItem11, 4, 3, 1, 1)
        self.filter_format = QtWidgets.QComboBox(self.filter_tab)
        self.filter_format.setObjectName("filter_format")
        self.filter_layout.addWidget(self.filter_format, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.filter_tab)
        self.label_10.setObjectName("label_10")
        self.filter_layout.addWidget(self.label_10, 5, 1, 1, 1)
        self.filter_split = QtWidgets.QCheckBox(self.filter_tab)
        self.filter_split.setChecked(True)
        self.filter_split.setObjectName("filter_split")
        self.filter_layout.addWidget(self.filter_split, 4, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.filter_tab)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.filter_layout.addWidget(self.line_7, 6, 1, 1, 2)
        self.clear_filter_btn = QtWidgets.QPushButton(self.filter_tab)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/erase.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_filter_btn.setIcon(icon5)
        self.clear_filter_btn.setObjectName("clear_filter_btn")
        self.filter_layout.addWidget(self.clear_filter_btn, 9, 0, 1, 1)
        self.filter_split_size = QtWidgets.QDoubleSpinBox(self.filter_tab)
        self.filter_split_size.setObjectName("filter_split_size")
        self.filter_layout.addWidget(self.filter_split_size, 5, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.load_filter_list_btn = QtWidgets.QPushButton(self.filter_tab)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.load_filter_list_btn.setIcon(icon6)
        self.load_filter_list_btn.setObjectName("load_filter_list_btn")
        self.horizontalLayout_2.addWidget(self.load_filter_list_btn)
        self.save_filter_list_btn = QtWidgets.QPushButton(self.filter_tab)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_filter_list_btn.setIcon(icon7)
        self.save_filter_list_btn.setObjectName("save_filter_list_btn")
        self.horizontalLayout_2.addWidget(self.save_filter_list_btn)
        self.filter_layout.addLayout(self.horizontalLayout_2, 10, 0, 1, 1)
        self.filter_layout.setColumnStretch(0, 1)
        self.verticalLayout_6.addLayout(self.filter_layout)
        self.aspects.addTab(self.filter_tab, icon4, "")
        self.resample_tab = QtWidgets.QWidget()
        self.resample_tab.setObjectName("resample_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.resample_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.resample_tab)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.resample_tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.resample_tab)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_4.addWidget(self.line_5, 2, 0, 1, 2)
        self.resample_split_size = QtWidgets.QDoubleSpinBox(self.resample_tab)
        self.resample_split_size.setDecimals(3)
        self.resample_split_size.setObjectName("resample_split_size")
        self.gridLayout_4.addWidget(self.resample_split_size, 5, 1, 1, 1)
        self.resample_split = QtWidgets.QCheckBox(self.resample_tab)
        self.resample_split.setChecked(True)
        self.resample_split.setObjectName("resample_split")
        self.gridLayout_4.addWidget(self.resample_split, 4, 0, 1, 1)
        self.resample_compression = QtWidgets.QComboBox(self.resample_tab)
        self.resample_compression.setObjectName("resample_compression")
        self.gridLayout_4.addWidget(self.resample_compression, 3, 1, 1, 1)
        self.resample_format = QtWidgets.QComboBox(self.resample_tab)
        self.resample_format.setMinimumSize(QtCore.QSize(200, 0))
        self.resample_format.setObjectName("resample_format")
        self.gridLayout_4.addWidget(self.resample_format, 1, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem13, 8, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.resample_tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 5, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.resample_tab)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_4.addWidget(self.line_6, 6, 0, 1, 2)
        self.resample_btn = QtWidgets.QPushButton(self.resample_tab)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/resample.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resample_btn.setIcon(icon8)
        self.resample_btn.setObjectName("resample_btn")
        self.gridLayout_4.addWidget(self.resample_btn, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.resample_tab)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.raster = QtWidgets.QDoubleSpinBox(self.resample_tab)
        self.raster.setDecimals(6)
        self.raster.setObjectName("raster")
        self.gridLayout_4.addWidget(self.raster, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.aspects.addTab(self.resample_tab, icon8, "")
        self.verticalLayout.addWidget(self.aspects)

        self.retranslateUi(file_widget)
        self.aspects.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(file_widget)

    def retranslateUi(self, file_widget):
        _translate = QtCore.QCoreApplication.translate
        file_widget.setWindowTitle(_translate("file_widget", "Form"))
        self.aspects.setTabText(self.aspects.indexOf(self.channels_tab), _translate("file_widget", "Channels"))
        self.convert_split_size.setSuffix(_translate("file_widget", "MB"))
        self.label_2.setText(_translate("file_widget", "Output format"))
        self.convert_split.setText(_translate("file_widget", "Split data blocks"))
        self.label_3.setText(_translate("file_widget", "Compression"))
        self.label_5.setText(_translate("file_widget", "Split size "))
        self.convert_btn.setText(_translate("file_widget", "Convert"))
        self.aspects.setTabText(self.aspects.indexOf(self.convert_tab), _translate("file_widget", "Convert"))
        self.aspects.setTabToolTip(self.aspects.indexOf(self.convert_tab), _translate("file_widget", "conv"))
        self.cut_split.setText(_translate("file_widget", "Split data blocks"))
        self.label_13.setText(_translate("file_widget", "Start"))
        self.label_7.setText(_translate("file_widget", "Split size [MB]"))
        self.cut_btn.setText(_translate("file_widget", "Cut"))
        self.label_6.setText(_translate("file_widget", "Compression"))
        self.label_15.setText(_translate("file_widget", "Output format"))
        self.cut_start.setSuffix(_translate("file_widget", "s"))
        self.cut_stop.setSuffix(_translate("file_widget", "s"))
        self.label_14.setText(_translate("file_widget", "End"))
        self.cut_interval.setText(_translate("file_widget", "TextLabel"))
        self.aspects.setTabText(self.aspects.indexOf(self.cut_tab), _translate("file_widget", "Cut"))
        self.label_21.setText(_translate("file_widget", "Type"))
        self.single_time_base.setText(_translate("file_widget", "Single time base"))
        self.time_from_zero.setText(_translate("file_widget", "Time from 0s"))
        self.label_22.setText(_translate("file_widget", "Raster"))
        self.use_display_names.setText(_translate("file_widget", "Use display names"))
        self.export_raster.setSuffix(_translate("file_widget", "s"))
        self.label_19.setText(_translate("file_widget", "Empty channels"))
        self.label_18.setText(_translate("file_widget", ".mat format"))
        self.export_btn.setText(_translate("file_widget", "Export"))
        self.aspects.setTabText(self.aspects.indexOf(self.export_tab), _translate("file_widget", "Export"))
        self.filter_btn.setText(_translate("file_widget", "Filter"))
        self.label_12.setText(_translate("file_widget", "Outpput format"))
        self.label_11.setText(_translate("file_widget", "Compression"))
        self.label_10.setText(_translate("file_widget", "Split size [MB]"))
        self.filter_split.setText(_translate("file_widget", "Split data blocks"))
        self.clear_filter_btn.setText(_translate("file_widget", "Clear selection"))
        self.load_filter_list_btn.setText(_translate("file_widget", "Load selection"))
        self.save_filter_list_btn.setText(_translate("file_widget", "Save selection"))
        self.aspects.setTabText(self.aspects.indexOf(self.filter_tab), _translate("file_widget", "Filter"))
        self.label_8.setText(_translate("file_widget", "Compression"))
        self.label_4.setText(_translate("file_widget", "Output format"))
        self.resample_split_size.setSuffix(_translate("file_widget", "MB"))
        self.resample_split.setText(_translate("file_widget", "Split data blocks"))
        self.label_9.setText(_translate("file_widget", "Split size"))
        self.resample_btn.setText(_translate("file_widget", "Resample"))
        self.label.setText(_translate("file_widget", "Raster"))
        self.raster.setSuffix(_translate("file_widget", "s"))
        self.aspects.setTabText(self.aspects.indexOf(self.resample_tab), _translate("file_widget", "Resample"))

from asammdfgui import resource_rc
